# Generated by Django 5.2.7 on 2025-11-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
