# Generated by Django 5.2.7 on 2025-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('farm_admin', 'Farm Admin'), ('agrovet', 'Agrovet'), ('vet', 'Vet')], default='farm_admin', max_length=20),
        ),
    ]
