# Generated by Django 5.2.7 on 2026-04-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='meat_withdrawal_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='milk_withdrawal_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PoultryVaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('vaccine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='E.g. 1 vial per 1000 birds, per litre, etc.', max_length=150)),
                ('route', models.CharField(choices=[('DW', 'Drinking Water'), ('SP', 'Spray'), ('ED', 'Eye Drop'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous')], max_length=2)),
                ('administered_by', models.CharField(max_length=100)),
                ('age_in_days', models.PositiveIntegerField(help_text='Age of birds at time of vaccination')),
                ('withdrawal_days', models.PositiveIntegerField(blank=True, help_text='Egg/meat withdrawal period', null=True)),
                ('next_booster_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='greenApp.poultrybatch')),
            ],
        ),
    ]
