# Generated by Django 5.2.7 on 2025-11-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Feed', 'Feed'), ('Vaccine', 'Vaccine'), ('Fertilizer', 'Fertilizer'), ('Seeds', 'Seeds'), ('Animal', 'Animal'), ('Equipment', 'Equipment'), ('Other', 'Other')], max_length=50)),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('supplier', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('total_cost', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
