# Generated by Django 5.2.7 on 2025-12-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyGoatFeedingSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_type', models.CharField(max_length=100)),
                ('feed_amount_per_day', models.FloatField()),
                ('feeding_frequency', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_schedules', to='greenApp.dairygoat')),
            ],
        ),
        migrations.CreateModel(
            name='DairyGoatFeedingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount_fed', models.FloatField()),
                ('time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='greenApp.dairygoatfeedingschedule')),
            ],
        ),
    ]
