# Generated by Django 5.2.7 on 2025-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0002_procurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('current_stock', models.FloatField()),
                ('min_threshold', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('unit_cost', models.FloatField()),
                ('supplier', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
