# Generated by Django 5.2.7 on 2025-11-08 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=150)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
