# Generated by Django 5.2.7 on 2025-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0002_recurringexpense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('utility', 'Utility'), ('services', 'Services')], max_length=20),
        ),
    ]
