# Generated by Django 5.2.7 on 2025-11-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0003_teamroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamroles',
            name='role_description',
            field=models.TextField(null=True),
        ),
    ]
