# Generated by Django 5.2.7 on 2025-12-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0003_birdsfeedingschedule_birdsfeedingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result_code', models.CharField(blank=True, max_length=20, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmVisitBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('number_of_visitors', models.PositiveIntegerField()),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00 AM - 11:00 AM', '09:00 AM - 11:00 AM'), ('11:00 AM - 01:00 PM', '11:00 AM - 01:00 PM'), ('02:00 PM - 04:00 PM', '02:00 PM - 04:00 PM'), ('04:00 PM - 06:00 PM', '04:00 PM - 06:00 PM')], max_length=50)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='greenApp.mpesapayment')),
            ],
        ),
    ]
