# Generated by Django 5.2.7 on 2025-11-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='egg_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egg_sales', to='greenApp.eggsale'),
        ),
        migrations.AddField(
            model_name='orders',
            name='goatmilk_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goatmilk_sales', to='greenApp.goatmilksale'),
        ),
        migrations.AddField(
            model_name='orders',
            name='milk_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milk_sales', to='greenApp.milksale'),
        ),
    ]
