# Generated by Django 5.2.7 on 2025-12-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0004_mpesapayment_farmvisitbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmvisitbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=50),
        ),
    ]
