# Generated by Django 5.2.7 on 2025-11-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0004_teamroles_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamroles',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='teamroles',
            name='role_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
