# Generated by Django 5.2.7 on 2025-11-09 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0005_teamroles_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('farm_size', models.CharField(blank=True, max_length=255, null=True)),
                ('farm_number', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
