# Generated by Django 5.2.7 on 2025-12-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('rabbit', 'Rabbit')], default='rabbit', max_length=20)),
                ('animal_name', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('buck', 'Buck'), ('doe', 'Doe')], max_length=10)),
                ('category', models.CharField(choices=[('does', 'Does'), ('bucks', 'Bucks'), ('growers', 'Growers'), ('kits', 'Kits')], max_length=50)),
                ('breed', models.CharField(blank=True, choices=[('californian', 'Californian'), ('chinchilla', 'Chinchilla'), ('flemish giant', 'Flemish Giant'), ('new zealand white', 'New Zealand White'), ('kenya white', 'Kenya White'), ('dutch', 'Dutch'), ('angora', 'Angora'), ('french loop', 'French Loop'), ('other', 'Other')], max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('cage_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('sold', 'Sold'), ('dead', 'Dead'), ('culled', 'Culled')], default='alive', max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired', to='greenApp.rabbit')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthed', to='greenApp.rabbit')),
            ],
        ),
    ]
