# Generated by Django 5.2.7 on 2025-12-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0005_farmvisitbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPlants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plot', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
