# Generated by Django 5.2.7 on 2025-11-11 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0006_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_alerts', models.BooleanField(default=False)),
                ('leave_requests', models.BooleanField(default=False)),
                ('payment_reminders', models.BooleanField(default=False)),
                ('health_reminders', models.BooleanField(default=False)),
                ('system_updates', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
