# Generated by Django 5.2.7 on 2025-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0006_farmplants_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
