# Generated by Django 5.2.7 on 2025-12-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0006_rabbit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('volume_liters', models.FloatField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatfishBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_type', models.CharField(choices=[('catfish', 'Catfish')], default='catfish', max_length=20)),
                ('quantity_stocked', models.IntegerField()),
                ('average_weight_at_stocking', models.FloatField()),
                ('stocking_date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('health_status', models.CharField(default='Healthy', max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='greenApp.pond')),
            ],
        ),
    ]
