# Generated by Django 5.2.7 on 2025-12-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0007_alter_plot_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
