# Generated by Django 5.2.7 on 2025-12-09 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0007_pond_catfishbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_type',
            field=models.CharField(choices=[('cow_milk', 'Cow Milk'), ('goat_milk', 'Goat Milk'), ('eggs', 'Eggs'), ('catfish', 'Catfish')], max_length=20),
        ),
        migrations.CreateModel(
            name='CatfishSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kilos', models.FloatField()),
                ('price_per_kilo', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catfish_sales', to='greenApp.customers')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='catfish_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catfish_sales', to='greenApp.catfishsale'),
        ),
    ]
