# Generated by Django 5.2.7 on 2025-12-13 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0009_alter_useraccount_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPlanting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('seed_quantity_used', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_unit', models.CharField(default='kg', max_length=20)),
                ('planting_notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='greenApp.farmplants')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='greenApp.plot')),
            ],
        ),
    ]
