# Generated by Django 5.2.7 on 2025-11-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0010_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'OnLeave'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('farm_admin', 'Farm Admin'), ('agrovet', 'Agrovet'), ('vet', 'Vet'), ('farm_worker', 'Farm Worker')], default='farm_worker', max_length=20),
        ),
    ]
