# Generated by Django 5.2.7 on 2025-12-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0010_cropplanting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplanting',
            name='status',
            field=models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested')], default='planted', max_length=20),
        ),
        migrations.CreateModel(
            name='CropHarvest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('quantity_harvested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('quality_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='greenApp.cropplanting')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fertilizer_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('application_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_applications', to='greenApp.cropplanting')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('irrigation_date', models.DateField()),
                ('water_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(default='liters', max_length=20)),
                ('method', models.CharField(default='manual', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigations', to='greenApp.cropplanting')),
            ],
        ),
        migrations.CreateModel(
            name='PesticideApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chemical_name', models.CharField(max_length=100)),
                ('pest_or_disease', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='liters', max_length=20)),
                ('application_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_applications', to='greenApp.cropplanting')),
            ],
        ),
    ]
