# Generated by Django 5.2.7 on 2025-12-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0011_cropplanting_status_cropharvest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
