# Generated by Django 5.2.7 on 2025-11-14 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0011_teammember_status_alter_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.IntegerField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='greenApp.teammember')),
            ],
        ),
    ]
