# Generated by Django 5.2.7 on 2025-12-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0012_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('vaccine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=150)),
                ('route', models.CharField(choices=[('SC', 'Subcutaneous'), ('IM', 'Intramuscular'), ('IN', 'Intranasal')], max_length=2)),
                ('administered_by', models.CharField(max_length=100)),
                ('milk_withdrawal_days', models.PositiveIntegerField()),
                ('meat_withdrawal_days', models.PositiveIntegerField()),
                ('next_booster_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='greenApp.dairycattle')),
            ],
        ),
    ]
