# Generated by Django 5.2.7 on 2025-12-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0013_vaccinationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poultrybatch',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
