# Generated by Django 5.2.7 on 2025-11-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0013_salary_salarypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyCattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('dairy', 'Dairy')], default='dairy', max_length=20)),
                ('animal_name', models.CharField(max_length=50, unique=True)),
                ('breed', models.CharField(blank=True, choices=[('ayshire', 'Ayshire'), ('boran', 'Boran'), ('brown swiss', 'Brown Swiss'), ('fleckvieh', 'Fleckvieh'), ('gurnsey', 'Gurnsey'), ('holstein friesian', 'Holstein Friesian'), ('jersey', 'Jersey'), ('red friesian', 'Red Friesian'), ('sahiwal', 'Sahiwal'), ('other', 'Other')], max_length=50, null=True)),
                ('tag_number', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('calf', 'Calf (0-4 months)'), ('weaner', 'Weaner (4-8 months)'), ('heifer', 'Heifer (9-10 months)'), ('yearling', 'Yearling (11-13 months)'), ('bulling heifer', 'Bulling Heifer (14-18 months)'), ('incalf heifer', 'Incalf Heifer'), ('dry', 'Dry (2 months to calving)'), ('milker', 'Milker (After Calving)'), ('bull', 'Bull (Male calves above 3 months)')], max_length=50, null=True)),
                ('sire', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_sire', models.CharField(blank=True, max_length=100, null=True)),
                ('dam', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_dam', models.CharField(blank=True, max_length=100, null=True)),
                ('lactations', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('ksb_no', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('milk_target', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
