# Generated by Django 5.2.7 on 2025-12-29 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0014_alter_poultrybatch_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('price_per_kilo', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_sales', to='greenApp.farmplants')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='crop_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_sales', to='greenApp.cropsale'),
        ),
    ]
