# Generated by Django 5.2.7 on 2025-11-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0015_milkcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('polygon', 'Polygon'), ('polyline', 'Polyline'), ('marker', 'Marker')], max_length=20)),
                ('category', models.CharField(choices=[('irrigation', 'Irrigation'), ('fencing', 'Fencing'), ('field', 'Field'), ('crop-zone', 'Crop Zone')], max_length=20)),
                ('coordinates', models.JSONField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
