# Generated by Django 5.2.7 on 2025-12-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0015_cropsale_orders_crop_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_sales', to='greenApp.customers'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_type',
            field=models.CharField(choices=[('cow_milk', 'Cow Milk'), ('goat_milk', 'Goat Milk'), ('eggs', 'Eggs'), ('catfish', 'Catfish'), ('crop', 'Crop')], max_length=20),
        ),
    ]
