# Generated by Django 5.2.7 on 2025-11-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0016_mapdrawing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoultryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('poultry', 'Poultry')], default='poultry', max_length=20)),
                ('category', models.CharField(choices=[('layers', 'Layers'), ('broilers', 'Broilers'), ('improved_kienyeji', 'Improved Kienyeji')], max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age_in_days', models.PositiveIntegerField()),
                ('number_of_chicks', models.PositiveIntegerField()),
                ('vaccinated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
