# Generated by Django 5.2.7 on 2026-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0016_alter_cropsale_customer_alter_orders_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vet_officer', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('routine_checkup', 'Routine Checkup'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('consultation', 'Consultation'), ('surgery', 'Surgery')], max_length=50)),
                ('animal_type', models.CharField(choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('poultry', 'Poultry'), ('rabbits', 'Rabbits'), ('catfish', 'Catfish'), ('other', 'Other')], max_length=50)),
                ('animal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('report_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date', '-added_on'],
            },
        ),
    ]
