# Generated by Django 5.2.7 on 2026-01-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0017_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairycattle',
            name='tag_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
