# Generated by Django 5.2.7 on 2025-11-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0017_poultrybatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalvingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField()),
                ('calf_name', models.CharField(max_length=255)),
                ('calf_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('complications', models.TextField(blank=True, null=True)),
                ('assistance_required', models.BooleanField(default=False)),
                ('veterinarian', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calving_records', to='greenApp.dairycattle')),
            ],
            options={
                'ordering': ['-calving_date'],
            },
        ),
    ]
