# Generated by Django 5.2.7 on 2025-11-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0018_calvingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('treatment_type', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('deworming', 'Deworming'), ('vaccination', 'Vaccination'), ('vitamin', 'Vitamin / Supplement'), ('other', 'Other')], max_length=50)),
                ('dosage', models.CharField(max_length=100)),
                ('administration_route', models.CharField(choices=[('oral', 'Oral'), ('injection', 'Injection'), ('topical', 'Topical'), ('intravenous', 'Intravenous'), ('other', 'Other')], max_length=50)),
                ('treatment_date', models.DateField()),
                ('prescribed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('next_dose_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='greenApp.dairycattle')),
            ],
        ),
    ]
