# Generated by Django 5.2.7 on 2025-11-20 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0019_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('total_eggs', models.PositiveIntegerField()),
                ('broken_eggs', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_collections', to='greenApp.poultrybatch')),
            ],
        ),
    ]
