# Generated by Django 5.2.7 on 2025-11-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0020_eggcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyGoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('dairy', 'Dairy')], default='dairy', max_length=20)),
                ('animal_name', models.CharField(max_length=50, unique=True)),
                ('breed', models.CharField(blank=True, choices=[('alpine', 'Alpine'), ('boer', 'Boer'), ('jamunapari', 'Jamunapari'), ('nigerian dwarf', 'Nigerian Dwarf'), ('saanen', 'Saanen'), ('toggenburg', 'Toggenburg'), ('other', 'Other')], max_length=50, null=True)),
                ('tag_number', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('kid', 'Kid (0-6 months)'), ('doeling', 'Doeling (Female kid 6-12 months)'), ('buckling', 'Buckling (Male kid 6-12 months)'), ('yearling', 'Yearling (12-18 months)'), ('bulling doe', 'Bulling Doe (18-24 months)'), ('in-calf doe', 'In-calf Doe'), ('dry doe', 'Dry Doe (2 months to kidding)'), ('milker', 'Milker (After Kidding)'), ('buck', 'Buck (Adult Male)')], max_length=50, null=True)),
                ('sire', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_sire', models.CharField(blank=True, max_length=100, null=True)),
                ('dam', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_dam', models.CharField(blank=True, max_length=100, null=True)),
                ('lactations', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('ksb_no', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('milk_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoatMilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField()),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('quantity', models.FloatField()),
                ('quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('collected_by', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_collections', to='greenApp.dairygoat')),
            ],
            options={
                'ordering': ['-collection_date', '-collection_time'],
            },
        ),
    ]
