# Generated by Django 5.2.7 on 2025-11-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0021_dairygoat_goatmilkcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairycattle',
            name='breed',
            field=models.CharField(blank=True, choices=[('alpine', 'Alpine'), ('saanen', 'Saanen'), ('toggenburg', 'Toggenburg'), ('anglo-nubian', 'Anglo-Nubian'), ('galla', 'Galla'), ('seag', 'Seag')], max_length=50, null=True),
        ),
    ]
