# Generated by Django 5.2.7 on 2025-11-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0026_goatmilksale'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trays', models.FloatField()),
                ('price_per_tray', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_sales', to='greenApp.customers')),
            ],
        ),
    ]
