# Generated by Django 5.2.7 on 2025-11-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0028_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='category',
            field=models.CharField(blank=True, choices=[('livestock', 'Livestock'), ('dairy', 'Dairy'), ('poultry', 'Poultry'), ('crop', 'Crop'), ('fish', 'Fish')], max_length=20, null=True),
        ),
    ]
