# Generated by Django 5.2.7 on 2025-11-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0030_recurringexpense_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
