# Generated by Django 5.2.7 on 2025-11-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenApp', '0031_alter_recurringexpense_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairycattle',
            name='breed',
            field=models.CharField(blank=True, choices=[('ayshire', 'Ayshire'), ('boran', 'Boran'), ('brown swiss', 'Brown Swiss'), ('fleckvieh', 'Fleckvieh'), ('gurnsey', 'Gurnsey'), ('jersey', 'Jersey'), ('sahiwal', 'Sahiwal'), ('red friesian', 'Red Friesian'), ('holstein friesian', 'Holstein Friesian')], max_length=50, null=True),
        ),
    ]
